### ISSUE TITLE
Houve problema na comunicação

### ISSUE THREAD

**Issue by crisanjo** [Ewersonfc/BBboleto#2]
Estou recebendo o erro abaixo quando envio um boleto.
Type: Ewersonfc\BBboleto\Exceptions\OAuthException
Message: Houve problema na comunicação
Filename: /var/www/html/sysz/vendor/ewersonfc/bbboleto/src/Clients/BancoDoBrasilAuthorizationClient.php

**Comment by Ewersonfc** [comment]
Boa tarde, 

Acredito que seja algo relacionado ao usuário e senha da API do banco. 

Em contato com eles você consegue obter esse usuário. 

$bancoDoBrasil = new BancoDoBrasil([
	'clientId' => 'xxxx',
	'clientSecret' => 'xxx',
	'production' => false,
	'formato' => 'html',
]);

Essa sessão está preenchida? 

Att..
